- id: doi:10.3389/fmed.2022.994467
  type: paper
  description: Tumor stroma reaction
  date: 2022-9-7
  image: https://www.frontiersin.org/files/Articles/994467/fmed-09-994467-HTML-r1/image_m/fmed-09-994467-g001.jpg
  buttons:
    - type: website
      text: Manuscript
      link: https://pubmed.ncbi.nlm.nih.gov/36160147/
    - type: source
      text: Source code
      link: https://github.com/smujiang/TumorStromaReaction
