- id: doi:10.1016/j.celrep.2018.03.076
  type: paper
  description: DNA damage repair, Genomic and Molecular Landscape, TCGA
  date: 2018-04-03
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124718304376-fx1.jpg
  buttons:
    - type: website
      text: Manuscript
      link: https://www.sciencedirect.com/science/article/pii/S2211124718304376?via%3Dihub
    - type: data
      text: Supplemental Data
      link: https://gdc.cancer.gov/about-data/publications/PanCan-DDR-2018
    
- id: doi:10.3389/fmed.2022.994467
  type: paper
  description: Tumor stroma reaction
  date: 2022-9-7
  image: https://www.frontiersin.org/files/Articles/994467/fmed-09-994467-HTML-r1/image_m/fmed-09-994467-g001.jpg
  buttons:
    - type: website
      text: Manuscript
      link: https://pubmed.ncbi.nlm.nih.gov/36160147/
    - type: source
      text: Source code
      link: https://github.com/smujiang/TumorStromaReaction




